<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="cosmo-logo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BACnet" Version="3.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Ressources\cosmo-logo.png" />
  </ItemGroup>
</Project>
